import { useState } from "react";
import { SiGithub, SiGoogleplay } from "react-icons/si";
import { Badge } from "@/components/ui/common/badge";
import { Button } from "@/components/ui/common/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/common/card";
import { GoLinkExternal } from "react-icons/go";
import { CardContainer, CardBody, CardItem } from "@/components/ui/aceternity/3d-card";

interface ProjectCardProps {
  title: string;
  description: string;
  techStack: string[];
  imageUrl: string;
  /** Optional srcSet for responsive images (e.g. "url-400w.webp 400w, url-800w.webp 800w"). Generated by npm run images. */
  imageSrcSet?: string;
  githubUrl?: string;
  playstore?: string;
  live?: boolean;
  duration?: string;
  onCardClick?: () => void;
}

export default function ProjectCard(props: ProjectCardProps) {
  const {
    title,
    description,
    techStack,
    imageUrl,
    imageSrcSet,
    live,
    githubUrl,
    playstore,
    duration,
    onCardClick,
  } = props;

  const repositoryUrl = githubUrl;

  const [imageLoaded, setImageLoaded] = useState(false);

  const handleCardKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (!onCardClick) return;
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      onCardClick();
    }
  };

  const cardContent = (
    <CardContainer className="inter-var h-full w-full">
      <CardBody className="w-full h-full">
        <CardItem
          translateZ="50"
          className="text-xl font-bold text-neutral-600 dark:text-[var(--text)] h-full transition-none w-full border-none outline-none"
        >
          <Card
            className="antialiased [text-rendering:optimizeLegibility] [&_*]:antialiased [&_*]:[text-rendering:optimizeLegibility] w-full max-w-none h-full shadow-lg hover:shadow-2xl transition-[transform,shadow] duration-300 ease-out relative group/card dark:hover:shadow-white/10 dark:border-white/[0.2] border-black/[0.1] flex flex-col mx-auto cursor-pointer"
            onClick={onCardClick}
            onKeyDown={handleCardKeyDown}
            role={onCardClick ? "button" : undefined}
            tabIndex={onCardClick ? 0 : undefined}
          >
            <CardHeader className="flex-shrink-0">
              <CardItem
                translateZ="60"
                className="w-full aspect-video rounded-2xl mb-2 overflow-hidden relative group-hover/image:opacity-80"
              >
                <img
                  src={imageUrl}
                  srcSet={imageSrcSet}
                  sizes="(max-width: 767px) 100vw, (max-width: 1200px) 50vw, 800px"
                  alt={title}
                  width={800}
                  height={450}
                  loading="lazy"
                  decoding="async"
                  onLoad={() => setImageLoaded(true)}
                  style={{ opacity: imageLoaded ? 1 : 0 }}
                  className="w-full h-full object-cover rounded-2xl transition-opacity duration-300 pointer-events-none"
                />
              </CardItem>
              <div className="text-xs text-neutral-500 dark:text-neutral-400 mb-1 transition-none">{duration}</div>
              <CardTitle className="flex items-center gap-2 transition-none text-gray-900 dark:text-[var(--text)]">
                {title}
                {live && (
                  <span className="inline-block h-2 w-2 rounded-2xl bg-emerald-500 -translate-y-0.5"></span>
                )}
              </CardTitle>
              <CardDescription className="transition-none">{description}</CardDescription>
            </CardHeader>
            <CardContent className="flex-shrink-0">
              <div className="flex flex-wrap gap-2">
                {techStack.map((tech, index) => (
                  <Badge
                    key={index}
                    variant="outline"
                    className="font-normal rounded-2xl transition-none"
                  >
                    {tech}
                  </Badge>
                ))}
              </div>
            </CardContent>
            <CardFooter className="flex justify-between items-center mt-auto">
              <div className="flex gap-2 items-center">
                {repositoryUrl && (
                  <div
                    className="flex items-center gap-2 text-sm font-medium px-3 h-9 cursor-default"
                    style={{ color: "var(--text)" }}
                  >
                    <SiGithub className="size-4" />
                    GitHub
                  </div>
                )}
                {playstore && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="transition-none cursor-pointer"
                    asChild
                    onClick={(e) => e.stopPropagation()}
                    onPointerDown={(e) => e.stopPropagation()}
                  >
                    <a
                      href={playstore}
                      target="_blank"
                      rel="noopener noreferrer"
                      onClick={(e) => e.stopPropagation()}
                      onPointerDown={(e) => e.stopPropagation()}
                      className="flex items-center gap-2 font-medium"
                      style={{ color: "var(--text)" }}
                    >
                      <SiGoogleplay className="size-4" />
                      App
                    </a>
                  </Button>
                )}
              </div>
              {repositoryUrl && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-emerald-500 dark:text-emerald-400 transition-none cursor-pointer"
                  asChild
                  onClick={(e) => e.stopPropagation()}
                  onPointerDown={(e) => e.stopPropagation()}
                >
                  <a
                    href={repositoryUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    onPointerDown={(e) => e.stopPropagation()}
                  >
                    <GoLinkExternal className="size-4" />
                  </a>
                </Button>
              )}
            </CardFooter>
          </Card>
        </CardItem>
      </CardBody>
    </CardContainer>
  );

  return cardContent;
}




